### ISSUE TITLE
ISO no longer bootable on Sun X4100 as of r151022

### ISSUE THREAD

**Issue by GeorgeBailey** [omniosorg/omnios-build#1030]
Tested on stable `omniosce-r151026.iso`, first OmniOSce release `omniosce-r151022s.iso` as&nbsp;well&nbsp;as&nbsp;the&nbsp;last&nbsp;OmniTI&nbsp;release&nbsp;`r151022.iso`.

![booting sun x4100 with omniosce-r151022s iso via ilom](https://user-images.githubusercontent.com/708850/46219981-d11f8200-c316-11e8-9418-e6c36d95045b.png)

    CD Loader 1.2
    
    Building the boot loader arguments
    Looking up /BOOT/ZFSLOADER... File not found
    Looking up /boot/zfsloader... Found
    Read Error: 0x20

Works fine on [`OmniOS_Text_r151020.iso`](https://omnios.omniti.com/media/OmniOS_Text_r151020.iso). So, for new servers I'll install that, Upgrade to `r151022`, and then [Switch to OmniOSce](https://omniosce.org/setup/switch.html), upgrading straight from OmniTI `r151022` to OmniOSce `r151026`.

**Comment by citrus-it** [comment]
Could you try our latest bloody media just to rule out the possibility that this has already been fixed?
https://downloads.omniosce.org/media/bloody/omniosce-bloody-20180928.iso

It looks like you can boot from grub but not from loader. OmniOS does still support grub for network installations so that might be an option for you: https://omniosce.org/setup/pxe - it's pretty straightforward to set up a kayak server on an existing installation, then you can build new servers from that.

**Comment by citrus-it** [comment]
Also, could you please test whether the .iso media at http://148.52.235.80.sta.estpak.ee/ boots for you? This is an OpenIndiana installer but it has some re-worked BIOS disk handling code.

**Comment by GeorgeBailey** [comment]
Dude! `omniosce-bloody-20180928.iso` worked! Thanks!

Now I'll be looking forward to the release of `r151028`. :-)

**Comment by GeorgeBailey** [comment]
Okay, so on another X4100 worked correctly. So that's good, that means the problems is much more limited and easily overcome in our datacenter.

I do not know what about the other X4100 hardware is different exactly. One X4100 has the error. The other does not.

I'd like to try those other ISO files as you suggested, but it will have to wait a week or two. Perhaps I'll reopen the issue then if I have helpful information for you.
