### ISSUE TITLE
update: developer/lexer/flex

### ISSUE THREAD

**Issue by citrus-it** [omniosorg/omnios-build#37]
2.6.0 -> 2.6.4

**Comment by ptribble** [comment]
This will need a fair bit of testing.

Generally, flex 2.6 caused a rather large amount of breakage, and 2.6.x updates just broke other stuff.  (We haven't seen this on OmniOS because we're on r151014 which still has the working 2.5.39, but certainly in Tribblix it got so bad I just reverted to 2.5.39 and have frozen it there.)

**Comment by citrus-it** [comment]
OmniOS has had flex 2.6.0 since r151018.
Flex 2.6.4 has lots of specific bug fixes for issues reported with 2.6.0 so we should incorporate those into bloody.
Since flex is used for building parts of OmniOS, I've run a full end-to-end test build using flex 2.6.4 and it was successful.
